qmicli: allow skipping CID release after successful operation
E.g. if the command requested will end up power cycling the device and
therefore not even supporting the cid release operation, as in the
"HP Change Device Mode" command.

    [22 ene 2017, 18:42:23] [Debug] [/dev/cdc-wdm1] sent generic request (translated)...
    <<<<<< QMUX:
    <<<<<<   length  = 16
    <<<<<<   flags   = 0x00
    <<<<<<   service = "ctl"
    <<<<<<   client  = 0
    <<<<<< QMI:
    <<<<<<   flags       = "none"
    <<<<<<   transaction = 2
    <<<<<<   tlv_length  = 5
    <<<<<<   message     = "Release CID" (0x0023)
    <<<<<< TLV:
    <<<<<<   type       = "Release Info" (0x01)
    <<<<<<   length     = 2
    <<<<<<   value      = 02:02
    <<<<<<   translated = [ service = 'dms' cid = '2' ]

    [22 ene 2017, 18:42:23] [Debug] [/dev/cdc-wdm1] sending message as MBIM...
    error: couldn't release client: MBIM error: Transaction timed out